version: '3'
services:
  api:
    image: vollmed-api:0.0.4
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/vollmed_api
      SPRING_DATASOURCE_USERNAME: igor
      SPRING_DATASOURCE_PASSWORD: 15269583
    volumes:
      - ../opentelemetry-javaagent.jar:/etc/opentelemetry-javaagent.jar
    ports:
      - "8080:8080"
    networks:
      - api-network
    depends_on:
      - mysql
  mysql:
    image: mysql:0.1.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 15269583
      MYSQL_USER: igor
      MYSQL_PASSWORD: 15269583
      MYSQL_DATABASE: vollmed_api
    networks:
      - api-network
networks:
  api-network:





